#!/bin/bash

odin build src                 \
    -debug                     \
    -vet                       \
    -strict-style              \
    -no-threaded-checker       \
    -terse-errors              \
    -max-error-count:5         \
    -collection:src=src        \
    -out:deboog
